packageExtensions:
  "@graphql-codegen/cli@*":
    dependencies:
      "@types/node": ^16.11.49
      ts-node: "*"
      typescript: ^4.8.2
  express@*:
    dependencies:
      hbs: "*"
  follow-redirects@*:
    dependencies:
      debug: "*"
  graphql-config@*:
    dependencies:
      "@types/node": ^16.11.49
      typescript: ^4.8.2

plugins:
  # NOTE: plugin-interactive-tools disabled due to RangeError on Windows when initializing the plugin.
  # If needed later, re-enable and update Yarn/Node accordingly.
  # - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  #   spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
